### ISSUE TITLE
dockerization of tuatara

### ISSUE THREAD

**Issue by BBO-repo** [jackvial/tuatara#10]
Hello Jack,
Thank for providing such a concise library for OCR.
I've tried it and it is definitively a good starting point to someone wanting to make deep learning OCR in C++.

I've dockerized your library to have it working out of the box, you can find it there https://github.com/BBO-repo/cpp-ocr-engine.
If you think that it makes sense to integrate it in your repository I can try make an PR.

Also I would be happy to help code and/or add feature and/or redesign your c++ tuatara project.

**Comment by jackvial** [comment]
Hi BBO-repo, just got back from vacation!

Happy to hear you're finding it to be a good jumping off point. 

Dockerizing the project definitely makes sense, your code looks solid, feel free to open a PR here for it. I'd like to optimize and target deploying on linux containers so this is inline with those goals 👍 

Also very happy to accept your help and contributions on this project 🙏

**Comment by BBO-repo** [comment]
Hi,
No problem for the delay. I'll try to make a PR soon and submit.
Nice that dockerization is in line with future works

Thanks, then let's go and after done, we'll see for other related works you would like to bring.
